version: '3'
services:
  node1:
    build: .
    entrypoint: "/scripts/start.sh"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - "./chain/:/var/eth"
      - "./scripts/:/scripts"
